-- Ejecutar una sola vez en el SQL Editor de Supabase (proyecto kclnaabvcxdovvgblyoc).
--
-- YA SE CORRIÓ (2026-09-16): docentes/evento_especial/evento_docente y
-- usuarios quedaron verificados contra el esquema que espera script.js,
-- con los 8 docentes, 3 eventos y 10 convocatorias existentes intactos.
-- Se deja el script en el repo como referencia/historial; volver a
-- correrlo no debería romper nada (todo está guardado con IF NOT EXISTS /
-- manejo de duplicate_object), pero ya no hace falta.
--
-- CONTEXTO: script.js se apuntó a este proyecto (el que tiene el historial
-- real: 5 docentes, 37 fichajes) pero su esquema relacional todavía es el
-- VIEJO (previo a la migración a multi-escuela / geocerca por evento /
-- recuperación de contraseña del admin), mientras que el código ya espera
-- el esquema NUEVO (el mismo que ya corre en el otro proyecto,
-- zyxcummfswlnaupvaqor). Este script lleva el esquema viejo al nuevo sin
-- perder los datos existentes:
--
--   docente (id_docente, dni, apellido, nombre, email, telefono, ...)
--     -> docentes (id, escuela_id, dni, nombre, apellido, email, telefono,
--                  password, calle, numero, barrio, localidad, provincia,
--                  pais, created_at)
--   evento_especial (id_evento, fecha, hora_entrada, hora_salida, lugar)
--     -> evento_especial (id, escuela_id, fecha_inicio, fecha_fin,
--                         tiene_geocerca, geocerca_lat, geocerca_lng,
--                         geocerca_radio, direccion_evento)
--   evento_docente (id_evento, id_docente)
--     -> evento_docente (evento_id, docente_id)
--   usuarios: no existe en este proyecto -> se crea (necesaria para poder
--     cambiar la contraseña del admin y para la recuperación por email;
--     hasta que se corra esto, el login admin sigue andando con el
--     usuario/clave por defecto ADMIN/SantaMarta hardcodeado en CONFIG).
--
-- Los ids existentes de `docente`/`evento_especial` se preservan tal cual
-- (solo se renombran las columnas), así que los vínculos ya guardados en
-- evento_docente siguen apuntando a la fila correcta sin necesidad de
-- remapear nada.
--
-- ANTES DE CORRER ESTO: conviene revisar si hay DNIs duplicados en
-- `docente` (la tabla nueva exige `dni` único porque el cliente hace
-- upsert con onConflict:'dni'):
--
--   select dni, count(*) from docente group by dni having count(*) > 1;
--
-- Si aparece algo, resolvé el duplicado a mano antes de seguir (este
-- script va a fallar al crear la constraint unique si hay colisiones).

-- ===== docente -> docentes =====
alter table docente rename to docentes;
alter table docentes rename column id_docente to id;

alter table docentes add column if not exists escuela_id integer not null default 2;
alter table docentes add column if not exists password text;
alter table docentes add column if not exists calle text;
alter table docentes add column if not exists numero text;
alter table docentes add column if not exists barrio text;
alter table docentes add column if not exists localidad text default 'RESISTENCIA';
alter table docentes add column if not exists provincia text default 'CHACO';
alter table docentes add column if not exists pais text default 'ARGENTINA';
alter table docentes add column if not exists created_at timestamptz not null default now();

-- Único por dni: es la clave que usa syncTeacherToDocenteTable() en
-- script.js para el upsert (onConflict:'dni').
do $$
begin
    alter table docentes add constraint docentes_dni_key unique (dni);
exception
    when duplicate_object then null;
end $$;

-- Los ids preservados (algunos son directamente el id de app_data.teachers,
-- valores grandes tipo Date.now()) se insertaron a mano, no por secuencia;
-- se limpia cualquier default viejo y se arma una identity nueva para los
-- docentes que se agreguen de acá en adelante sin pisar los ids existentes
-- (arranca en 500000, muy por debajo de los ids tipo Date.now() y muy por
-- encima de los ids chicos ya usados).
alter table docentes alter column id drop default;
do $$
begin
    alter table docentes alter column id add generated by default as identity (start with 500000);
exception
    when others then null; -- ya tiene identity de una corrida anterior
end $$;

-- ===== evento_especial: fecha/hora_entrada/hora_salida -> fecha_inicio/fecha_fin =====
alter table evento_especial rename column id_evento to id;

alter table evento_especial add column if not exists escuela_id integer not null default 2;
alter table evento_especial add column if not exists fecha_inicio timestamp;
alter table evento_especial add column if not exists fecha_fin timestamp;
alter table evento_especial add column if not exists tiene_geocerca boolean not null default false;
alter table evento_especial add column if not exists geocerca_lat double precision;
alter table evento_especial add column if not exists geocerca_lng double precision;
alter table evento_especial add column if not exists geocerca_radio integer;
alter table evento_especial add column if not exists direccion_evento text;

update evento_especial
set fecha_inicio = (fecha::text || 'T' || hora_entrada::text)::timestamp,
    fecha_fin    = (fecha::text || 'T' || hora_salida::text)::timestamp,
    direccion_evento = coalesce(direccion_evento, lugar)
where fecha_inicio is null;

alter table evento_especial alter column fecha_inicio set not null;
alter table evento_especial alter column fecha_fin set not null;

-- La constraint UNIQUE vieja (fix_unique_evento.sql) estaba sobre
-- (titulo, fecha, hora_entrada); esas columnas se borran abajo, así que
-- hay que sacarla antes de poder dropear las columnas.
alter table evento_especial drop constraint if exists unique_evento_dia_horario;

alter table evento_especial drop column if exists fecha;
alter table evento_especial drop column if exists hora_entrada;
alter table evento_especial drop column if exists hora_salida;
alter table evento_especial drop column if exists lugar;

-- Constraint equivalente sobre las columnas nuevas (mismo propósito:
-- frenar el doble clic en "Guardar" - ver saveEvento() en script.js).
do $$
begin
    alter table evento_especial add constraint unique_evento_titulo_inicio unique (titulo, fecha_inicio);
exception
    when duplicate_object then null;
end $$;

-- ===== evento_docente: id_evento/id_docente -> evento_id/docente_id =====
alter table evento_docente rename column id_evento to evento_id;
alter table evento_docente rename column id_docente to docente_id;

-- ===== usuarios (no existía en este proyecto) =====
-- Misma tabla y mismas políticas RLS "anon" abiertas que ya existen en
-- zyxcummfswlnaupvaqor (ver la advertencia de seguridad de
-- supabase_schema.sql: esta app no usa Supabase Auth, así que cualquiera
-- con la clave publishable puede leer/escribir esto si se deja así).
create table if not exists usuarios (
    id serial primary key,
    usuario text not null unique,
    password text not null,
    rol text not null default 'admin',
    email text,
    email_respaldo text,
    reset_token text,
    reset_token_expira timestamptz,
    updated_at timestamptz not null default now()
);

alter table usuarios enable row level security;

drop policy if exists "usuarios_select_anon" on usuarios;
create policy "usuarios_select_anon" on usuarios
    for select
    to anon
    using (true);

drop policy if exists "usuarios_insert_anon" on usuarios;
create policy "usuarios_insert_anon" on usuarios
    for insert
    to anon
    with check (true);

drop policy if exists "usuarios_update_anon" on usuarios;
create policy "usuarios_update_anon" on usuarios
    for update
    to anon
    using (true)
    with check (true);

-- Fila del admin con el usuario/clave por defecto (CONFIG.ADMIN_USER /
-- CONFIG.ADMIN_PASS en script.js). El email queda vacío a propósito -no
-- se hardcodea en un archivo versionado-; la propia app lo va a pedir en
-- el primer login (ver "E-MAIL OBLIGATORIO DEL ADMIN" en script.js).
insert into usuarios (usuario, password, rol)
values ('ADMIN', 'SantaMarta', 'admin')
on conflict (usuario) do nothing;

-- RLS de docentes/evento_especial/evento_docente: los renames de arriba
-- conservan las políticas que ya estaban en fix_rls_eventos.sql (están
-- atadas a la tabla, no al nombre), así que no hace falta recrearlas.

notify pgrst, 'reload schema';
